### ISSUE TITLE
大神  能否加你QQ咨询你一下尼尔存档问题

### ISSUE THREAD

**Issue by DjentM** [jimmyazrael/NierAutoModSave#1]
大神  能否加你QQ咨询你一下尼尔存档问题

**Comment by jimmyazrael** [comment]
称不上大神啦。我现在不怎么用QQ了，不如你在这里说说你的问题？

**Comment by DjentM** [comment]
回复及时  感动···
是这样的，是不是一旦切换STEAM账号   就会出现覆盖存档的问题？

**Comment by jimmyazrael** [comment]
应该是的，因为Nier游戏总是会使用Document\My Games下的同一个目录，建议将Nier存档文件夹整个备份后再切换账号。

**Comment by DjentM** [comment]
实在不好意思打扰你了   昨天忙着没回复你的回答 
是这样的   我遇到了切换账号造成的存档覆盖问题  
然后根据你的方法中：（4. 打开GameData.dat，选中括号中位置的数值（块：F-36，长度：28），粘帖，保存；）
这个步骤里的F-36我始终找不到，然后我尝试不修改此处，问题居然也解决了。
好奇心重，就想学习一下，此处这个数值是修改什么的？

**Comment by jimmyazrael** [comment]
不好意思，我猜是我在那里写错了，回去检查一下。

手边没有文件，时间也比较久远了，没记错的话，这个是存档文件slot 0的header，包含存档日期和截止到该存档的游戏时间等等。所以每个slot的存档都会有这个header。

你不改当然可以，不过就是继续沿用你原本slot 0的header而已。header和文件内容关系不大。

**Comment by DjentM** [comment]
噢   明白了   涨姿势了  感谢感谢！用你的方法  尼尔存档真心方便太多了
